@startuml Diagramme des classes d'utilisation
left to right direction

/' DÉFINITION DES ACTEURS '/
/' Acteurs humains '/
:Clients: as Ac_Client
:Conseillers: as Ac_Conseiller
:Administrateurs: as Ac_Admin

/' Acteurs systèmes '/
:Système de paiement: as Sys_Paiement
:Système de vérification d'adresse: as Sys_Adresse
:Système d'investissement: as Sys_Invest
:Système de notification: as Sys_Notif

/' DÉFINITION DES CAS D'UTILISATION '/
rectangle "Application Bancaire" as APPLI {

package "Système de paiement"{
    usecase "Se connecter" as PAI_0
    usecase "Vérifier le solde" as PAI_1
    usecase "Effectuer un virement" as PAI_2
    usecase "Demander un prêt" as PAI_3
    usecase "Consulter les comptes clients" as PAI_4
    usecase "Approuver un prêt" as PAI_5
}

package "Investissements" {
    usecase "Consulter portefeuille et performance" as INVEST_0
    usecase "Recevoir conseils selon profil de risque" as INVEST_1
    usecase "Acheter et/ou vendre une action" as INVEST_2
  }

package "Documents" {
    usecase "Télécharger relevés et documents" as DOC_0
    usecase "Soumettre document" as DOC_1
    usecase "Reçevoir notification de nouveau document" as DOC_2
  }
}

/' ASSOCIATIONS ENTRE ACTEURS/SYSTÈMES ET CAS D'UTILISATION '/
/' Clients '/
:Clients: --> PAI_1
:Clients: --> PAI_2
:Clients: --> PAI_3

:Clients: --> INVEST_0
:Clients: --> INVEST_1
:Clients: --> INVEST_2

/' Conseillers '/
PAI_4 <-- :Conseillers:
PAI_5 <-- :Conseillers:

/' Administrateurs '/

/' Systèmes '/


@enduml